<?php

return [
    'role_aliases' => [
        'System Administrator' => 'System Admin',
    ],

    'permissions' => [
        'Super Admin' => [
            'dashboard.view',
            'users.manage',
            'roles.assign',
            'settings.manage',
            'logs.view',
            'risks.view',
            'risks.create',
            'risks.update',
            'risks.delete',
            'incidents.view',
            'incidents.create',
            'incidents.update',
            'incidents.delete',
            'policies.view',
            'policies.create',
            'policies.update',
            'policies.delete',
            'policies.acknowledge',
            'policies.acknowledgments.view',
            'compliance.view',
            'compliance.create',
            'compliance.update',
            'compliance.delete',
            'audits.view',
            'audits.create',
            'audits.update',
            'audits.delete',
            'audits.report',
        ],
        'System Admin' => [
            'dashboard.view',
            'users.manage',
            'settings.manage',
            'logs.view',
            'backup.maintain',
            'security.monitor',
            'risks.view',
            'incidents.view',
            'incidents.update',
            'policies.view',
            'policies.create',
            'policies.update',
            'policies.delete',
            'policies.acknowledgments.view',
            'compliance.view',
            'compliance.create',
            'compliance.update',
            'compliance.delete',
            'audits.view',
            'audits.create',
            'audits.update',
            'audits.delete',
            'audits.report',
        ],
        'Compliance Officer' => [
            'dashboard.view',
            'risks.view',
            'policies.view',
            'policies.create',
            'policies.update',
            'policies.acknowledgments.view',
            'compliance.view',
            'compliance.create',
            'compliance.update',
            'audits.view',
            'audits.report',
        ],
        'Internal Auditor' => [
            'dashboard.view',
            'compliance.view',
            'audits.view',
            'audits.create',
            'audits.update',
            'audits.delete',
            'audits.report',
            'logs.view',
        ],
        'Department Manager' => [
            'dashboard.view',
            'risks.view',
            'risks.create',
            'risks.update',
            'incidents.view',
            'incidents.create',
            'incidents.update',
        ],
        'Employee' => [
            'dashboard.view',
            'incidents.view',
            'incidents.create',
            'policies.view',
            'policies.acknowledge',
        ],
    ],
];
